name: AWS Code EC2 Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write    
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_DEPLOY_ROLE_ARN }}:role/CiCD-Testing-Github
          aws-region: us-east-1

      - name: Deploy via SSM

        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "GitHub Actions deploy policy-executed-api" \
            --targets "Key=InstanceIds,Values=${{ vars.EC2_INSTANCE_ID }}" \
            --parameters commands='[
              "set -e",
              "mkdir -p /var/www",

              "cd /var/www",
              "sudo apt-get update -y",
              "sudo apt-get install -y git python3-venv",


              "if [ ! -d policy-executed-api ]; then git clone https://github.com/Nicholas-devsec/policy-executed-api.git; fi",
              "cd policy-executed-api",
              "git pull",

              "if [ ! -d .venv ]; then python3 -m venv .venv; fi",
              ". .venv/bin/activate",
             ".venv/bin/pip install --upgrade pip",
             ".venv/bin/pip install -r requirements.txt",


              "cp policy-executed-api.service /etc/systemd/system/",
              "systemctl daemon-reload",
              "systemctl enable policy-executed-api",
              "systemctl restart policy-executed-api",

              "echo Deployment successful"
            ]'